### ISSUE TITLE
service_url_for_direct_upload return NotImplementedError

### ISSUE THREAD

**Issue by Pash-tet** [ashishprajapati/activestorage-dropbox#16]
Hello. I use this gem for create graphql direct upload. I try create upload link for client like this:

```
input = {
  filename: "image_picker3738150546794568742.jpg",
  byte_size: 345010,
  checksum: "a74ff97376f874def3fb61ba642ac689",
  content_type: "image/jpeg"
}

blob = ActiveStorage::Blob.create_before_direct_upload!(input)

blob.service_url_for_direct_upload 
```

and receive NotImplementedError (NotImplementedError)

**Comment by ashishprajapati** [comment]
Thanks @Pash-tet

Yes, we didn't implement the`url_for_direct_upload` method because Dropbox API Ruby SDK didn't provide the API service to develop it that.

This method `get_temporary_upload_link` is not implemented in the Dropbox API Ruby SDK so we are unable to implement that feature in `activestorage-dropbox gem` .
Ref: https://github.com/Jesus/dropbox_api/blob/master/api_coverage.md

I will talk to the Dropbox API Ruby SDK team to figure out it and I will raise the PR to them. So, we can implement that feature in `activestorage-dropbox gem`.
